// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/map": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/gallery" | "/home" | "/map";
  };
  "routes/gallery.tsx": {
    id: "routes/gallery";
    page: "/gallery";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/map.tsx": {
    id: "routes/map";
    page: "/map";
  };
};