// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/:uuid": {
    params: {
      "uuid": string;
    };
  };
  "/favorites": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/gallery" | "/:uuid" | "/favorites";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/gallery.tsx": {
    id: "routes/gallery";
    page: "/gallery";
  };
  "./routes/$uuid.tsx": {
    id: "routes/$uuid";
    page: "/:uuid";
  };
  "./routes/favorites.tsx": {
    id: "routes/favorites";
    page: "/favorites";
  };
};